name: Build package documentation
description: use pkgdown to build and deploy package documentation
inputs:
    deps:
      description: Dependecies to check, used as "dependecies" parameter in "revdep_check()".
      required: false
      default: 'c("Depends", "Imports", "Suggests", "LinkingTo")'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3

    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: release
        use-public-rspm: true

    - uses: r-lib/actions/setup-pandoc@v2


    - uses: r-lib/actions/setup-r-dependencies@v2
    
    - name: Install revdepcheck
      run: |
        pak::pkg_install("r-lib/revdepcheck")
      shell: Rscript {0}

    - name: Check reverse dependencies -  ${{ inputs.deps }}
      env:
        _R_CHECK_CRAN_INCOMING_REMOTE_: false
      run: |
        revdepcheck::revdep_check(timeout = as.difftime(60, units = 'mins'),
                                  num_workers = 3,
                                  dependencies = ${{ inputs.deps }})
        problems <- readLines('revdep/problems.md', warn = FALSE)
        if (length(problems) > 1) stop(paste0(problems, collapse= "\n"))
      shell: Rscript {0}

    - name: Upload check results
      if: failure() && ${{ inputs.deps }} == ${{ inputs.deps.default }}
      uses: actions/upload-artifact@main
      with:
        name: revdep-results
        path: revdep/*.md

    - name: Upload check results - ${{ inputs.deps }}
      if: failure() && ${{ inputs.deps }} != ${{ inputs.deps.default }}
      uses: actions/upload-artifact@main
      with:
        name: revdep-${{ inputs.deps }}-results
        path: revdep/*.md
