name: Benchmark R Package
description: Installs and benchmarks an R package in a given subdirectory

inputs:
  path:
    description: Subdirectory containing the package to benchmark
    required: true
  output:
    description: Output folder to store benchmark .Rds files
    required: true

runs:
  using: "composite"
  steps:
    - name: Install and benchmark package from path
      run: |
        echo "::group::Checking for previous installation"
        PACKAGE_NAME=$(Rscript -e "cat(basename(normalizePath('.')))")                
        if Rscript -e "if ('$PACKAGE_NAME' %in% rownames(installed.packages())) quit(status = 1)" ; then
          echo "❌ Package '$PACKAGE_NAME' is already installed in default libPaths()"
          echo "Please ensure the environment is clean before benchmarking."
          echo "Installed packages:"
          Rscript -e "print(installed.packages()[, 1])"
          exit 1
        fi
        echo "::endgroup::"
      
        echo "::group::Installing from ${{ inputs.path }}"
        cd "${{ inputs.path }}"
        # Create and export a temp library directory
        LIB_DIR=$(mktemp -d)
        export R_LIBS="$LIB_DIR"
        
        R CMD INSTALL . --library="$LIB_DIR" \
          --preclean --clean --byte-compile \
          --no-docs --no-help --no-test-load --no-multiarch
        echo "::endgroup::"

        echo "::group::Cleaning temp files"
        pkill -f 'R --' || true
        rm -rf /tmp/R* /tmp/R_sess* || true
        echo "::endgroup::"

        echo "::group::Running benchmark for ${{ inputs.path }}"
        cd ../pr
        R_LIBS="$LIB_DIR" Rscript benchmark/_run_benchmarks.R
        
        echo "Writing output to ${{ inputs.output }}-benchmark-results"
        mkdir -p "./${{ inputs.output }}-benchmark-results"
        mv *.bench.Rds "./${{ inputs.output }}-benchmark-results"
        ls -lh "${{ inputs.output }}-benchmark-results"
        echo "::endgroup::"
        
        echo "::group::Cleaning temporary library"
        rm -rf "$LIB_DIR"
        echo "::endgroup::"
      shell: bash
