name: Benchmark R Package
description: Installs and benchmarks an R package in a given subdirectory

inputs:
  path:
    description: Subdirectory containing the package to benchmark
    required: true
  output:
    description: Output folder to store benchmark .Rds files
    required: true

runs:
  using: "composite"
  steps:
    - working-directory: "${{ inputs.path }}"
      name: Install and benchmark package from path
      run: |
        echo "::group::Installing from ${{ inputs.path }}"
        R CMD INSTALL . --library=$(mktemp -d) \
          --preclean --clean --byte-compile \
          --no-docs --no-help --no-test-load --no-multiarch
        echo "::endgroup::"

        echo "::group::Cleaning temp files"
        pkill -f 'R --' || true
        rm -rf /tmp/R* || true
        rm -rf /tmp/R_sess* || true
        echo "::endgroup::"

        echo "::group::Running benchmark for ${{ inputs.path }}"
        cd ../pr
        Rscript benchmark/_run_benchmarks.R
        echo "Writing output to ${{ inputs.output }}-benchmark-results"
        mkdir -p "./${{ inputs.output }}-benchmark-results"
        mv *.bench.Rds "./${{ inputs.output }}-benchmark-results"
        dir "${{ inputs.output }}-benchmark-results"
        echo "::endgroup::"
      shell: bash
