name: Check for memory errors
description: use valgrind to check for memory usage errors
inputs:
    test:
      description: Which aspect of the package to test. Select "tests", "examples", "vignettes" or "all".
      required: false
      default: all
    extra-repositories:
      description: Extra repositories, passed to r-lib/actions/setup-r
      required: false

runs:
  using: 'composite'
  steps:
    - name: Checkout git repo
      uses: actions/checkout@v4
      
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: release # CRAN uses devel, but takes ages to load deps.
        extra-repositories: ${{ inputs.extra-repositories }}

    - name: Install apt packages
      run: |
        sudo apt-get install valgrind
      shell: bash
      
    - name: Install package dependencies
      run: |
        install.packages("devtools")
        devtools::install_deps(dependencies = TRUE)
      shell: Rscript {0}
      
    - name: Initialize ASan configuration for valgrind
      run: |
        echo "PKG_CFLAGS = -g -O0 -fsanitize=address -fno-omit-frame-pointer" > src/Makevars
        echo "PKG_CXXFLAGS = -g -O0 -fsanitize=address -fno-omit-frame-pointer" >> src/Makevars
      shell: bash

    - name: valgrind - memcheck tests
      if: ${{ inputs.test }} == "tests" || ${{ inputs.test }} == "all"    
      run: |
        export LD_PRELOAD=$(gcc -print-file-name=libasan.so)
        R -d "valgrind --tool=memcheck \
        --leak-check=full \
        --track-origins=yes \
        --errors-for-leak-kinds=definite \
        --error-exitcode=1" \
        --vanilla 
        -e "devtools::test()"
      shell: bash

    - name: valgrind - memcheck examples
      if: ${{ inputs.test }} == "examples" || ${{ inputs.test }} == "all"    
      run: |
        R -d "valgrind --tool=memcheck \
        --leak-check=full \
        --track-origins=yes \
        --errors-for-leak-kinds=definite \
        --error-exitcode=1" \
        --vanilla 
        -e "devtools::run_examples()"
      shell: bash

    - name: Set up pandoc
      if: ${{ inputs.test }} == "vignettes" || ${{ inputs.test }} == "all"
      uses: r-lib/actions/setup-pandoc@v2
      
    - name: valgrind - memcheck vignettes
      if: ${{ inputs.test }} == "vignettes" || ${{ inputs.test }} == "all"    
      run: |
        sudo apt-get install texlive-latex-base
        R -d "valgrind --tool=memcheck \
        --leak-check=full \
        --errors-for-leak-kinds=definite \
        --error-exitcode=1" \
        --vanilla 
        -e "devtools::build_vignettes(install = FALSE)"
      shell: bash
