name: Write codemeta
description: Write codemeta to codemeta.json file
inputs:
    run-only:
      description: Skip the setup steps and run directly, assuming that setup was run.
      required: false
      default: false
    user-email:
      description: E-mail address to which commit should be attributed
      required: false
      default: 'actions@github.com'
    user-name:
      description: User name to which commit should be attributed
      required: false
      default: 'GitHub Actions'
    commit-message:
      description: Commit message to associate with commit
      required: false
      default: 'Update codemeta.json'

runs:
  using: 'composite'
  steps:
    - if: inputs.run-only != 'true'
      uses: actions/checkout@v3

    - if: inputs.run-only != 'true'
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: release

    - if: inputs.run-only != 'true'
      name: Set up R dependencies (Windows)
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: codemeta

    - name: Build metadata
      run: "codemeta::write_codemeta()"
      shell: Rscript {0}

    - name: Deploy metadata
      run: |
        git config --local user.email "${{ inputs.user-email }}"
        git config --local user.name "${{ inputs.user-name }}"
        git add codemeta.json
        git commit -m "${{ inputs.commit-message }}"
        git fetch
        git pull
        git push
      shell: bash
